Update fail.yml

diff --git a/.github/workflows/fail.yml b/.github/workflows/fail.yml
--- a/.github/workflows/fail.yml
+++ b/.github/workflows/fail.yml
@@ -11,5 +11,5 @@ jobs:
   fail:
     steps:
       - run: |
-        echo "Failure!"
-        exit 1
+          echo "Failure!"
+          exit 1
